// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_prueba/test/features/auth/data/respositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_prueba/features/auth/data/dataSources/i_authentication_source.dart'
    as _i3;
import 'package:flutter_prueba/features/auth/domain/entities/authentication_user.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthenticationUser_0 extends _i1.SmartFake
    implements _i2.AuthenticationUser {
  _FakeAuthenticationUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthenticationSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthenticationSource extends _i1.Mock
    implements _i3.IAuthenticationSource {
  MockIAuthenticationSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signUp(String? email, String? password, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password, name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> validate(String? email, String? validationCode) =>
      (super.noSuchMethod(
            Invocation.method(#validate, [email, validationCode]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resetPassword(
    String? email,
    String? newPassword,
    String? validationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [
              email,
              newPassword,
              validationCode,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> verifyToken() =>
      (super.noSuchMethod(
            Invocation.method(#verifyToken, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthenticationUser> getLoggedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUser, []),
            returnValue: _i4.Future<_i2.AuthenticationUser>.value(
              _FakeAuthenticationUser_0(
                this,
                Invocation.method(#getLoggedUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.AuthenticationUser>);

  @override
  _i4.Future<List<_i2.AuthenticationUser>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i4.Future<List<_i2.AuthenticationUser>>.value(
              <_i2.AuthenticationUser>[],
            ),
          )
          as _i4.Future<List<_i2.AuthenticationUser>>);

  @override
  _i4.Future<bool> addUser(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#addUser, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
